apiVersion: v2
name: hubble-authz-proxy
description: Namespace-scoped authorization proxy for the Hubble UI
type: application
version: 0.6.0
appVersion: 0.6.0
icon: >-
  https://raw.githubusercontent.com/splattner/hubble-authz-proxy/main/doc/images/hubble-authz-proxy-mark.png
home: https://github.com/splattner/hubble-authz-proxy
sources:
  - https://github.com/splattner/hubble-authz-proxy
keywords:
  - cilium
  - hubble
  - authorization
  - multi-tenancy
maintainers:
  - name: splattner
    url: https://github.com/splattner
