apiVersion: v2
name: hubble-authz-proxy
description: Namespace-scoped authorization proxy for the Hubble UI
type: application
version: 0.2.0
appVersion: 0.2.0
home: https://github.com/splattner/hubble-authz-proxy
sources:
  - https://github.com/splattner/hubble-authz-proxy
keywords:
  - cilium
  - hubble
  - authorization
  - multi-tenancy
maintainers:
  - name: splattner
    url: https://github.com/splattner
